server:
  port:  8081
  
spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3307/microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    
    

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
 
# for getting configuration from github config server
#  config:
#    import: options :configserver:http://localhost:8085
#  cloud:
#    config:
#      uri:
#      - configserver:http://localhost:8085

  

  config:
    import: optional:configserver:http://localhost:8085
    
#oauth client configurations  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-11992782.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
           provider: okta
           authorization-grant-type: client_credentials 
           scope: internal
           client-id: 0oaa8v2c7c9Qbt9YS5d7
           client-secret: 5stcpZvPjgR6YLjXGI6lOiOexUTBn7mgJtcLWaDK
        
        provider:
          okta:
            issuer-uri: https://dev-11992782.okta.com/oauth2/default       
  
#  profiles:
#    active: "prod"  
    
    
  
    
    
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka


#configuration for Resilience4j


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
      web:
       exposure:
          include: health
          
         
          
  endpoint:
    health:
      show-details: always
      
      
resilience4j:
  circuitbreaker:
    instances: 
      ratingHotelFallback:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        failureRateThreshold: 50
        minimum-number-of-calls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED 
        
        
      
# retry
  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s
        
        
#RateLimiter

  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2s
        
        
        

        
        
# OKTA Configurations
        
okta:
  oauth2:
    issuer: https://dev-11992782.okta.com/oauth2/default
    audience: api://default        
      
        
                  
    
   
         
   
      