server:
  port: 8083
  
spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/microservices
      database: microservices 
      
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
 
    
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka   
      
      
      
#Configuration For OKTA
okta:
  oauth2:
    issuer: https://dev-11992782.okta.com/oauth2/default
    audience: api://default           
      
      
    